// Biblioteca de características pré-criadas de criaturas (JUJUTSU LEGACY).
// Usada pelo seletor "Biblioteca" do editor de NPC — ao escolher uma entrada,
// ela é inserida na lista correspondente da ficha (aspectos / ações de poder /
// bônus / reação). O texto entre parênteses no nome indica o efeito no ND.
//
// `nd`: nota do impacto no Nível de Desafio (informativo). `recarga`: gatilho.

export const NPC_CATALOG = {
  // ── Aspectos (passivos durante o combate) ────────────────────────────────
  aspecto: [
    { nome: 'Absorção de Eletricidade', desc: 'Sempre que a criatura for alvo de dano Elétrico, ela não sofre dano e recupera Pontos de Vida igual ao dano Elétrico recebido.' },
    { nome: 'Agarrador', desc: 'A criatura tem vantagem nas jogadas de ataque contra qualquer criatura agarrada por ela.' },
    { nome: 'Agressivo', desc: 'Com uma ação bônus, a criatura se move até metade do seu deslocamento até um alvo hostil que ela possa ver.' },
    { nome: 'Andar em Teias', desc: 'A criatura ignora as restrições de movimento causadas por teias.' },
    { nome: 'Andar no Gelo', desc: 'Pode se mover em superfícies congeladas sem Teste de Atributo. Terreno difícil de gelo/neve não custa movimento extra.' },
    { nome: 'Anfíbio', desc: 'A criatura é capaz de respirar na terra e debaixo d\'água.' },
    { nome: 'Aparência Falsa', desc: 'Enquanto permanecer imóvel, é indistinguível de um outro objeto ou estrutura.' },
    { nome: 'Ataque Surpresa', desc: 'Se surpreender um alvo e atingi-lo na primeira rodada do encontro, o alvo sofre dano extra nesse ataque.' },
    { nome: 'Ataques Múltiplos', desc: 'A criatura pode fazer uma jogada de ataque mais de uma vez por turno.' },
    { nome: 'Audição Aguçada', desc: 'Vantagem em Testes de Espírito (Percepção) relacionados à audição.' },
    { nome: 'Aura de Medo', desc: 'Alvo hostil que comece o turno a até 6m (e a criatura não esteja incapacitada) faz Salvaguarda de Espírito; se falhar, fica "Amedrontado" até o início do próximo turno dele. Sucesso → imune por 24h.' },
    { nome: 'Cabeça Dura', desc: 'Ao fazer Salvaguarda para não receber "Atordoado", a criatura tem vantagem no teste.' },
    { nome: 'Camuflagem', desc: 'Vantagem em Testes de Agilidade (Furtividade), relacionados à pele/pelugem, para se esconder em um ambiente.' },
    { nome: 'Carapaça Reflexiva', desc: 'Contra projéteis (ataque à distância), role d6: 1-5 não é afetada; 6 não é afetada e o ataque é refletido de volta no atacante.' },
    { nome: 'Carnívoro Voraz', desc: 'Alvo Médio ou menor, feito de carne, que caia a 0 PV por ataque da criatura é devorado, restando apenas os ossos.' },
    { nome: 'Corpo Indomável', desc: 'Vantagem em Salvaguardas contra "Amedrontado", "Atordoado", "Enfeitiçado", "Envenenado", "Paralisado" ou posto para dormir.' },
    { nome: 'Corpo Inerte', desc: 'Ao fazer Salvaguarda para não ser empurrado, a criatura tem vantagem.' },
    { nome: 'Corpo Minúsculo', desc: 'A criatura tem vantagem em Salvaguardas e Atributo de Agilidade.' },
    { nome: 'Corpo Resistente', nd: 'Dobra o PV efetivo da criatura', desc: 'Contra ataque corpo-a-corpo, role d6: 4-5 não é afetada; 6 não é afetada e metade do dano (arred. p/ baixo) volta ao atacante.' },
    { nome: 'Couro Farpado', nd: 'Aumenta o dano efetivo por rodada', desc: 'No começo de cada turno, causa dano Perfurante a qualquer criatura agarrando-a ou sendo agarrado.' },
    { nome: 'Eco Localização', desc: 'A criatura não pode usar sua percepção às cegas enquanto estiver surda.' },
    { nome: 'Emboscador', desc: 'Vantagem nas jogadas de ataque contra qualquer criatura que ela tenha surpreendido.' },
    { nome: 'Enxame', desc: 'Pode ocupar o espaço de outra criatura e mover-se por aberturas de inseto Miúdo. Não pode recuperar PV nem ganhar PV temporários.' },
    { nome: 'Escalada Aracnídea', desc: 'Pode escalar superfícies difíceis, incluindo tetos de cabeça para baixo, sem Teste de Atributo.' },
    { nome: 'Escalada', desc: 'Pode escalar superfícies difíceis sem Teste de Atributo.' },
    { nome: 'Escavador', desc: 'Pode escavar rocha sólida com metade do deslocamento de escavação, deixando um túnel de 4,5m de diâmetro.' },
    { nome: 'Estabilidade', desc: 'Vantagem em Salvaguardas de Força e Agilidade contra efeitos que possam derrubá-la.' },
    { nome: 'Evasão', desc: 'Em efeito com Salvaguarda por metade do dano: sucesso = nenhum dano; falha = metade.' },
    { nome: 'Faro Aguçado', desc: 'Vantagem em Testes de Espírito (Percepção) relacionados ao olfato.' },
    { nome: 'Fedor', nd: 'Aumenta a CR efetiva em 1', desc: 'Alvo que comece o turno a até 1,5m faz Salvaguarda de Constituição ou fica "Envenenado" até o início do próximo turno dele. Sucesso → imune por 24h.' },
    { nome: 'Ferimento Enfurecedor', desc: 'Com menos da metade do PV: vantagem nas jogadas de ataque e dano extra nos ataques corpo-a-corpo.' },
    { nome: 'Frenesi de Sangue', nd: 'Aumenta o bônus de ataque efetivo em 4', desc: 'Vantagem nos ataques corpo-a-corpo contra qualquer criatura que não esteja com todos os PV.' },
    { nome: 'Fúria', desc: 'Ao começar o turno com menos da metade do PV, role d6; em 6 entra em fúria e ataca o alvo mais próximo a cada turno (ou um objeto, se não houver alvo). Continua até recuperar todo o PV.' },
    { nome: 'Fúria Vingativa', desc: 'Ao cair abaixo de metade dos PV pela 1ª vez: +1d6 de dano em todos os ataques até o fim do encontro.' },
    { nome: 'Implacável', desc: 'Dano que a reduziria a 0 PV a reduz a 1 PV. Recarrega após descanso curto ou longo.' },
    { nome: 'Luz Própria', desc: 'Cria luz de parte do corpo: esfera de 6m de luz direta + 3m de penumbra.' },
    { nome: 'Monstro de Cerco', desc: 'Causa o dobro de dano a objetos e estruturas.' },
    { nome: 'Movimentação Livre', desc: 'Ignora terreno difícil e não tem o deslocamento reduzido. Pode gastar 1,5m para escapar de impedimentos ou agarrão.' },
    { nome: 'Natureza Robótica', desc: 'Não precisa respirar, comer, beber ou dormir.' },
    { nome: 'Pele Escorregadia', desc: 'Qualquer criatura que tente agarrá-la recebe desvantagem.' },
    { nome: 'Percepção às Cegas', desc: 'Percebe seus arredores sem depender de visão dentro de um raio de 9m.' },
    { nome: 'Planar', desc: 'Desde que as asas não estejam presas, não recebe dano de queda.' },
    { nome: 'Prender a Respiração', desc: 'A criatura pode prender a respiração por 1 hora.' },
    { nome: 'Presença Aterradora', nd: 'Aumenta em 25% o PV efetivo de criaturas com ND 10 ou menor', desc: 'Alvo a até 18m que a veja faz Salvaguarda de Espírito ou fica "Amedrontado" por 1 min (repete no fim de cada turno, desvantagem se na linha de visão). Sucesso/fim → imune por 24h.' },
    { nome: 'Presença de Líder', desc: 'Aliados que a vejam a até 9m somam 1d8 a jogadas de acerto/Salvaguarda (só uma por vez). Termina se a criatura ficar "Incapacitada".' },
    { nome: 'Reativo', desc: 'A criatura pode realizar uma reação em cada turno no combate.' },
    { nome: 'Reflexo', desc: 'Jogadas de ataque contra a criatura têm desvantagem. Interrompido até o fim do próximo turno se for atingida, ou enquanto "Incapacitada"/deslocamento 0.' },
    { nome: 'Regeneração', nd: 'Aumenta os PV efetivos em 3× o PV regenerado por rodada', desc: 'Recupera PV no início de cada turno, se tiver pelo menos 1 PV.' },
    { nome: 'Respirar na Água', desc: 'A criatura só pode respirar embaixo d\'água.' },
    { nome: 'Salto Parado', desc: 'Salto em distância de até 15m e em altura de até 9m, com ou sem corrida.' },
    { nome: 'Sentidos Aguçados', desc: 'Vantagem em Testes de Espírito (Percepção) relacionados à audição, olfato e visão.' },
    { nome: 'Sobrevoo', desc: 'Não provoca Ataque de Oportunidade ao voar para fora do alcance de um inimigo.' },
    { nome: 'Táticas de Bando', desc: 'Vantagem nos ataques contra um alvo se um aliado não incapacitado estiver a 1,5m do alvo.' },
    { nome: 'Vantagem Marcial', nd: 'Aumenta o dano efetivo por rodada', desc: 'Uma vez por turno, dano extra a um alvo atingido com arma se um aliado não incapacitado estiver a 1,5m do alvo.' },
    { nome: 'Visão Aguçada', desc: 'Vantagem em Testes de Espírito (Percepção) relacionados à visão.' },
    { nome: 'Visão Noturna', desc: 'Vê na escuridão até 18m (penumbra como luz, escuridão como penumbra), apenas em tons de cinza.' },
  ],

  // ── Ações Bônus da criatura ──────────────────────────────────────────────
  acaoBonus: [
    { nome: 'Agarrar com a Cauda', nd: 'Aumenta o bônus de ataque efetivo em 1', desc: 'Ação bônus: ataque corpo-a-corpo desarmado; ao acertar, em vez de dano, o alvo fica agarrado. Vantagem nos ataques corpo-a-corpo contra ele (um alvo por vez).' },
    { nome: 'Agressivo', desc: 'Ação bônus: move-se até metade do deslocamento até um alvo hostil que possa ver.' },
    { nome: 'Chefe', desc: 'Ao errar ataque ou falhar Teste/Salvaguarda, ganha bônus igual ao nº de aliados a até 9m (máx +10). 5×/dia, recarrega após descanso longo.' },
    { nome: 'Furtividade Sombria', nd: 'Aumenta a CR efetiva em 2', desc: 'Na penumbra ou escuridão, pode realizar a ação "Esconder-se" com uma ação bônus.' },
    { nome: 'Múltiplos Membros', desc: 'Ação bônus: uma jogada de ataque (se não usou/usar "atacar"), "Usar um Objeto" ou "Guardar e Sacar" armas iguais à qtd de membros extras.' },
  ],

  // ── Ações de Poder da criatura ───────────────────────────────────────────
  acaoPoder: [
    { nome: 'Ataque com Asas', nd: 'Aumenta o dano efetivo por rodada (acertando duas criaturas)', desc: 'Alvos a até 6m fazem Salvaguarda de Agilidade ou sofrem (½ND↑)d6 de dano Contundente e ficam "Caídos". Depois a criatura voa até metade do deslocamento.' },
    { nome: 'Ataque de Mergulho', nd: 'Aumenta o dano efetivo na primeira rodada', desc: 'Se voando e mergulhar ≥6m em linha reta e atingir um alvo corpo-a-corpo, causa (½ND↑)d10 de dano adicional.' },
    { nome: 'Bote Sônico', nd: 'Aumenta o dano efetivo na primeira rodada', desc: 'Percorrendo ≥6m em linha reta livre até o alvo, lança-se e ataca corpo-a-corpo com (½ND↑)d10 de dano adicional; alvo faz Salvaguarda de Força ou cai. Não provoca ataque de oportunidade.' },
    { nome: 'Bote', nd: 'Aumenta o dano efetivo na primeira rodada', desc: 'Movendo ≥6m até o alvo e atacando corpo-a-corpo, o alvo faz Salvaguarda de Força ou fica "Caído". Se cair, ação bônus p/ novo ataque.' },
    { nome: 'Corte Sangrento', recarga: '5×/dia', desc: 'Uma vez por turno, após acertar corpo-a-corpo com arma cortante, o alvo faz Salvaguarda de Constituição ou fica "Sangramento". 5×/dia, recarrega após descanso longo.' },
    { nome: 'Cuspir Veneno', desc: 'Ataque à distância (até 6m); ao acertar, alvo faz Salvaguarda de Constituição ou fica "Envenenado" por 1 min (depois imune 24h).' },
    { nome: 'Descuidado', desc: 'No início do turno, ganha vantagem em todos os ataques corpo-a-corpo, mas ataques contra ela têm vantagem até o início do próximo turno.' },
    { nome: 'Impacto Atordoante', nd: 'Aumenta o bônus de ataque efetivo em 3', desc: 'Uma vez por rodada, ao causar dano Contundente, o alvo faz Salvaguarda de Constituição ou fica "Atordoado" até o fim do próximo turno dele.' },
    { nome: 'Inflar', desc: 'A criatura aumenta de tamanho para "Enorme" e não recebe dano de queda.' },
    { nome: 'Investida Derrubadora', nd: 'Aumenta o dano efetivo na primeira rodada', desc: 'Movendo ≥3m até o alvo e atacando corpo-a-corpo, dano Contundente extra; alvo faz Salvaguarda de Força (CD) ou é empurrado 6m e cai.' },
    { nome: 'Investida', nd: 'Aumenta o dano efetivo na primeira rodada', desc: 'Movendo ≥3m até o alvo e atacando corpo-a-corpo, o alvo sofre dano extra.' },
    { nome: 'Soltar Tinta', desc: 'Ação: solta tinta num cone de 6m; alvos que usem os olhos fazem Salvaguarda de Agilidade ou ficam "Cego" até limpar/ser coberto por água corrente.' },
    { nome: 'Teia', nd: 'Aumenta a CR efetiva em 1', desc: 'Ataque à distância com arma (9/18m) contra alvo Grande ou menor; ao acertar, "Impedido". Ação + Teste de Força escapa. Teia: CR 10, 5 PV, resist. Contundente, imune Psíquico/Veneno.' },
  ],

  // ── Reações da criatura ──────────────────────────────────────────────────
  reacao: [
    { nome: 'Apanhar Pedra', desc: 'Ao ser alvo de pedras/objetos similares, com Salvaguarda de Força, apanha o projétil sem sofrer dano Contundente.' },
    { nome: 'Aparar', nd: 'Aumenta a CR efetiva em 1', desc: '+5 na CR contra um ataque corpo-a-corpo. Precisa ver o atacante e empunhar arma corpo-a-corpo.' },
    { nome: 'Ataque de Oportunidade Superior', nd: 'Aumenta o bônus de ataque efetivo em 2', desc: 'Se um alvo sair do alcance voluntariamente (mesmo sem provocar), ataque corpo-a-corpo; se acertar, deslocamento do alvo vira 0 até o fim da rodada.' },
    { nome: 'Ataque de Oportunidade Traiçoeiro', nd: 'Aumenta o bônus de ataque efetivo em 3', desc: 'Ataque de oportunidade quando um inimigo visível se move para fora OU para dentro do alcance corpo-a-corpo, voluntariamente.' },
    { nome: 'Ataque de Oportunidade Orgulhoso', nd: 'Aumenta o bônus de ataque efetivo em 2', desc: 'Se um alvo atacar outra criatura (não você) a até 1,5m, ataque corpo-a-corpo contra esse alvo.' },
    { nome: 'Ataque de Oportunidade', nd: 'Aumenta o bônus de ataque efetivo em 1', desc: 'Ataque de oportunidade corpo-a-corpo quando um inimigo visível sai do alcance corpo-a-corpo, voluntariamente.' },
    { nome: 'Defletir Projéteis', nd: 'Aumenta a CR efetiva em 2', desc: 'Empunhando arma corpo-a-corpo e vendo o atacante, defle todos os projéteis do turno: dano reduzido em 4d10; se zerar, totalmente evitado.' },
    { nome: 'Redirecionar Ataque', desc: 'Ao receber um ataque visível, escolhe um aliado de ND menor a até 1,5m; trocam de lugar e o aliado vira o alvo.' },
    { nome: 'Casco Protetor', nd: 'Aumenta a CR efetiva em 2', desc: 'Ao receber ataque, entra no casco: +5 na CR, fica "Incapacitado" e deslocamento 0. Gasta uma ação para sair.' },
  ],

  // ── Maldições — Habilidades de Ação de Poder (espírito) ──────────────────
  espiritoPoder: [
    { nome: 'Abalo Sísmico', desc: 'Uma vez por rodada: tremor em raio = 3× ND. Voadores caem; em terra, Salvaguarda de Agilidade ou "Caído". Quem falhar sofre d6 = metade do ND (arred. p/ baixo).' },
    { nome: 'Aura de Terror', desc: 'Aura em raio (m) = 3× ND. No início de cada turno, criaturas na área fazem Salvaguarda de Sabedoria; falha → d6 de dano psíquico = ⅓ do ND (arred. p/ cima).' },
    { nome: 'Carne Amaldiçoada', desc: 'Ataque infecta a carne. Ao ser atingida, Salvaguarda de Intelecto; falha → d6 = metade do ND e 1d6 verdadeiro sempre que agir/mover.' },
    { nome: 'Dimensão Instável', desc: 'Área de raio 6m que cresce 6m por turno (máx 3× ND). Dentro: Salvaguardas −2; espírito tem vantagem em ataque; quem entra pela 1ª vez sofre metade do ND em d6 Verdadeiro. Dura 1 min.' },
    { nome: 'Lamento Desesperador', desc: 'Grito por distância: até 3m → Salvaguarda de Sabedoria, falha d6=½ ND + "Inconsciente"; 4,5-9m → falha d6=½ ND + "Incapacitado"; 10,5m+ → "Surdo". (Sucesso = metade do dano.)' },
    { nome: 'Parasita Amaldiçoado', desc: 'Ataque injeta energia; alvo faz Salvaguarda de Intelecto; falha → d6 = ⅓ do ND no início de cada turno do espírito. Repete a Salvaguarda no fim de cada turno.' },
    { nome: 'Distorção Espacial', desc: 'Até o fim do próximo turno: +3 na própria CR e pode teleportar 1×/rodada em alcance 3× ND sem gastar ação.' },
    { nome: 'Barreira Negativa', desc: 'Cubo de energia ao redor de uma criatura: impede visão/movimento; PV = 10× ND, CR 15; impede teletransporte (se maldição espacial). Dura 3 rodadas; 1 cubo por 5 ND.' },
    { nome: 'Dreno de Vitalidade', desc: 'Absorve vitalidade em raio = 3× ND. Salvaguarda de Intelecto; falha → d6 = ½ ND e o espírito recupera metade do dano causado.' },
    { nome: 'Revelar Forma', desc: 'Por 1 min: dano adicional = próprio ND em todas as fontes; ataques ignoram resistências/invulnerabilidades; perde todas as próprias resistências.' },
    { nome: 'Invocação Fragmentada', desc: 'Cria um clone idêntico sacrificando 1 Ponto de Atributo; clone tem metade dos PV. Se destruído, recupera o atributo após descanso longo. Toca o clone (ação) para reabsorver.' },
    { nome: 'Colapso Interno', desc: 'Golpe injeta energia: d10 = ½ ND. Salvaguarda de Constituição; falha → "Letárgico" até o fim do próximo turno.' },
    { nome: 'Prisão do Medo', desc: 'Alvo a até 3× ND preso em ilusão de terror. Salvaguarda de Sabedoria; falha → "Atordoado" até sofrer dano ou 1h. Repete no fim do turno (1d8 psíquico/rodada presa).' },
    { nome: 'Chuva Amaldiçoada', desc: 'Área de raio = 3× ND a até 60m. Salvaguarda de Constituição; falha → d6 de dano ácido = ½ ND (sucesso = metade).' },
    { nome: 'Olhar Aterrador', desc: 'Fixa o olhar em alvo a até 3× ND. Salvaguarda de Sabedoria ou "Paralisado" enquanto mantiver o olhar e não atacar outro. Repete no fim do turno.' },
    { nome: 'Sobrecarga de Energia', desc: 'Por 1 min: +1 dado + ND em todo dano. Sofre 3 de dano adicional de todas as fontes enquanto ativa.' },
    { nome: 'Letargia Constante', desc: 'Por 1 min, área de raio = 3× ND. No início do turno, Salvaguarda de Constituição; falha → desvantagem em Salvaguardas físicas e 2d8 de dano direto à vida.' },
    { nome: 'Eco Doloroso', recarga: '4-6', desc: 'Alvo a até 3× ND faz Salvaguarda de Sabedoria; falha → sofre como psíquico todo o dano que recebeu no último turno (sucesso = metade). Cada falha dá +2 na próxima tentativa.' },
    { nome: 'Explosão Elemental', desc: 'Se sofreu dano desde o turno anterior: explosão de d8 elemental = ½ ND (arred. p/ cima) em raio = 1,5× ND. Salvaguarda de Agilidade (sucesso = metade).' },
    { nome: 'Fragmentação de Realidade', desc: 'Por 2 rodadas: 1 ataque (Comum) adicional por rodada; toda rolagem de acerto rola 1d4 e falha automática em 1-2. 3×/encontro.' },
    { nome: 'Presença Opressora', desc: 'Por 1 min, no início do turno, área de raio = 3× ND: Salvaguarda de Força; falha → "Pesado" até o início do próximo turno do espírito.' },
    { nome: 'Fome Voraz', desc: 'Ao se aproximar a 1,5m de criatura incapacitada com 0 PV, toca para absorvê-la: recupera metade do PV máximo (máx 150). A criatura morre instantaneamente.' },
    { nome: 'Vinhas Amaldiçoadas', desc: 'Vinhas em raio 3× ND: Salvaguarda de Força ou d6 = ½ ND + "Impedido".' },
    { nome: 'Sopro Corrosivo', desc: 'Cone 1,5× ND: Salvaguarda de Agilidade; falha → d8 ácido = ½ ND (sucesso = metade).' },
    { nome: 'Maldição da Cegueira', desc: 'Alvo a 3× ND faz Salvaguarda de Intelecto ou "Cego" por 1 min (repete no fim do turno).' },
    { nome: 'Pulso de Podridão', desc: 'Área 3× ND: Salvaguarda de Constituição; falha → d6 de energia = ½ ND e reduz PV máx no mesmo valor.' },
    { nome: 'Toque Petrificante', desc: 'Ataque CaC; Salvaguarda de Constituição → "Impedido" e, na falha seguinte, "Petrificado".' },
    { nome: 'Enxame Devorador', desc: 'Enxame em raio 3× ND por 1 min: quem inicia o turno na área sofre d6 = ½ ND e desvantagem em ataques.' },
    { nome: 'Veneno Persistente', desc: 'Ataque à distância; Salvaguarda de Constituição → "Envenenado" e d6 = ⅓ ND por turno (repete).' },
    { nome: 'Grito Dissonante', desc: 'Área 3× ND: Salvaguarda de Constituição; falha → d6 psíquico = ⅓ ND + "Surdo".' },
    { nome: 'Chamas Espectrais', desc: 'Área 1,5× ND: Salvaguarda de Agilidade; falha → d6 fogo = ½ ND + "Queimado".' },
    { nome: 'Lâminas de Vácuo', desc: 'Linha 3× ND: Salvaguarda de Agilidade; falha → d8 cortante = ½ ND + "Sangramento".' },
    { nome: 'Domínio do Frio', desc: 'Área 3× ND por 1 min: Salvaguarda de Constituição; falha → d6 gelo = ½ ND + "Hipotérmico"; 2 falhas → "Congelado".' },
    { nome: 'Miragem Cruel', desc: 'Alvo a 3× ND faz Salvaguarda de Sabedoria ou "Alucinado".' },
    { nome: 'Corrente de Almas', desc: 'Correntes em raio 3× ND: Salvaguarda de Força; falha → d6 = ½ ND e puxado 6m.' },
    { nome: 'Maldição do Peso', desc: 'Alvo a 3× ND faz Salvaguarda de Força ou "Pesado" (se já estiver, "Caído").' },
    { nome: 'Explosão de Esporos', desc: 'Área 3× ND: Salvaguarda de Constituição; falha → d6 = ⅓ ND + "Sonolento".' },
    { nome: 'Olhar Hipnótico', desc: 'Alvo a 3× ND faz Salvaguarda de Sabedoria ou "Enfeitiçado" (termina se sofrer dano).' },
    { nome: 'Mãos da Sepultura', desc: 'Mãos em raio 3× ND: Salvaguarda de Agilidade; falha → d6 = ½ ND + "Agarrado".' },
    { nome: 'Pústulas Explosivas', desc: 'Ataque CaC; ao sofrer o próximo dano, explode: d8 = ½ ND nele e a 1,5m.' },
    { nome: 'Cântico Enlouquecedor', desc: 'Por 1 min, área 3× ND: Salvaguarda de Presença; falha → d6 psíquico = ⅓ ND e desvantagem no próximo ataque.' },
    { nome: 'Maré de Ácido', desc: 'Área 3× ND: Salvaguarda de Agilidade; falha → d6 ácido = ½ ND e −1 CR até o fim do turno.' },
  ],

  // ── Maldições — Habilidades de Ação Bônus (espírito) ─────────────────────
  espiritoBonus: [
    { nome: 'Ataque de Garra', desc: 'Ação bônus: uma jogada de ataque (Comum) adicional contra qualquer criatura.' },
    { nome: 'Passo Distorcido', desc: 'Ação bônus: desaparece e se materializa a até 3× ND. Não provoca reações como Ataque de Oportunidade.' },
    { nome: 'Golpes Disformes', desc: 'Ação bônus: +1,5m de alcance e bônus de acerto = ½ ND (arred. p/ baixo) até o fim do turno.' },
    { nome: 'Revestimento Maldito', desc: 'Ação bônus: resistência a dano Contundente, Cortante e Perfurante até o fim do próximo turno.' },
    { nome: 'Marca Efêmera', desc: 'Ação bônus: rolagem de ataque para tocar e marcar; o próximo dano que o alvo receber faz a marca explodir: d6 = 1/2 do ND (arred. p/ cima).' },
    { nome: 'Avanço Predatório', desc: 'Ação bônus: dispara até uma criatura a >6m; se alcançar, a próxima rolagem de ataque é com vantagem.' },
    { nome: 'Sussurros da Loucura', desc: 'Ação bônus: alvo a até 3× ND faz Salvaguarda de Presença; falha → desvantagem na próxima rolagem de ataque.' },
    { nome: 'Recuperação Rápida', desc: 'Ação bônus: recupera d8 de PV = ½ ND; não mais que metade do dano que sofreu.' },
    { nome: 'Expulsão Violenta', desc: 'Ação bônus: criaturas a até 6m fazem Salvaguarda de Força ou são empurradas 1,5m × ND. Colisão com estrutura → d8 contundente = ½ ND (arred. p/ cima).' },
    { nome: 'Olhar Desconcertante', desc: 'Ação bônus: enquanto focar só nesse alvo, ele não obtém vantagem contra o espírito. Em troca, −1 na CR do espírito contra as demais criaturas.' },
    { nome: 'Instinto do Assassinato', desc: 'Ação bônus: ignora bônus de CR de qualquer fonte que não seja Habilidade Básica/Treinamento até o início do próximo turno.' },
    { nome: 'Forma Etérea', desc: 'Ação bônus: torna-se intangível até o fim do turno, atravessando criaturas/objetos e ignorando ataques/dano. Não pode atacar nem atravessar estruturas/barreiras.' },
    { nome: 'Rastro Amaldiçoado', desc: 'Ação bônus: cada quadrado por onde passar causa dano até o início do próximo turno; quem entrar/passar sofre 1d8 (tipo à escolha do narrador).' },
    { nome: 'Bote Sombrio', desc: 'Ação bônus: mergulha nas sombras e ressurge a 3× ND; próximo ataque com vantagem.' },
    { nome: 'Casulo Regenerativo', desc: 'Ação bônus: recupera d8 PV = ½ ND; não pode reagir até o próximo turno.' },
    { nome: 'Salto Aberrante', desc: 'Ação bônus: salta até 1,5× ND sem provocar reações.' },
    { nome: 'Garras Dilacerantes', desc: 'Ação bônus: ataque (Comum) adicional; em acerto, Salvaguarda de Constituição ou "Sangramento".' },
    { nome: 'Véu de Sombras', desc: 'Ação bônus: ataques contra o espírito com desvantagem até o próximo turno.' },
    { nome: 'Sopro Gélido', desc: 'Ação bônus: alvo a 6m faz Salvaguarda de Constituição; falha → d6 gelo = ⅓ ND + "Hipotérmico".' },
    { nome: 'Pele de Aço', desc: 'Ação bônus: +2 CR até o próximo turno, mas deslocamento pela metade.' },
    { nome: 'Investida Espectral', desc: 'Ação bônus: avança 6m e colide; alvo faz Salvaguarda de Força ou "Caído".' },
    { nome: 'Lamúria Aterradora', desc: 'Ação bônus: alvo a 3× ND faz Salvaguarda de Sabedoria ou "Amedrontado".' },
    { nome: 'Drenagem Tátil', desc: 'Ação bônus: toque a 1,5m causa d6 = ⅓ ND e recupera PV igual ao dano.' },
    { nome: 'Aceleração Maldita', desc: 'Ação bônus: deslocamento dobra e não provoca reações até o fim do turno.' },
    { nome: 'Cuspe Aprisionante', desc: 'Ação bônus: alvo a 6m faz Salvaguarda de Agilidade ou "Impedido" até o próximo turno.' },
    { nome: 'Reconfigurar Membros', desc: 'Ação bônus: +1,5m de alcance OU +3m de deslocamento até o próximo turno.' },
    { nome: 'Marca de Caça', desc: 'Ação bônus: marca um alvo a 3× ND: +1 acerto e +1d6 de dano contra ele.' },
    { nome: 'Esporos Cegantes', desc: 'Ação bônus: alvo a 3m faz Salvaguarda de Constituição ou "Cego" até o próximo turno.' },
    { nome: 'Sussurro Confuso', desc: 'Ação bônus: alvo a 3× ND faz Salvaguarda de Presença ou não pode reagir até o próximo turno.' },
    { nome: 'Tentáculo Súbito', desc: 'Ação bônus: ataque (Comum) adicional a 3m; em acerto, "Agarrado".' },
    { nome: 'Camuflagem Cromática', desc: 'Ação bônus: se não se mover, fica "Invisível" até o próximo turno ou até atacar.' },
    { nome: 'Mordida Infecciosa', desc: 'Ação bônus: ataque (Comum) adicional; em acerto, Salvaguarda de Constituição ou "Envenenado".' },
    { nome: 'Fenda Instável', desc: 'Ação bônus: troca de lugar com criatura a 3× ND (Salvaguarda de Sabedoria resiste).' },
    { nome: 'Toque Entorpecente', desc: 'Toque a 1,5m: Salvaguarda de Constituição ou "Letárgico" até o próximo turno do espírito.' },
    { nome: 'Marca da Fraqueza', desc: 'Marca um alvo a 3× ND: desvantagem na próxima Salvaguarda dele.' },
    { nome: 'Olhar Vil', desc: 'Alvo a 3× ND: Salvaguarda de Sabedoria ou "Amedrontado" até o próximo turno.' },
    { nome: 'Jato Cegante', desc: 'Alvo a 6m: Salvaguarda de Agilidade ou "Cego" até o próximo turno.' },
    { nome: 'Estalo Ensurdecedor', desc: 'Criaturas a 3m: Salvaguarda de Constituição ou "Surdo" até o próximo turno.' },
    { nome: 'Toque Adormecedor', desc: 'Toque a 1,5m: Salvaguarda de Constituição ou "Sonolento" até o próximo turno.' },
    { nome: 'Presas Peçonhentas', desc: 'Ataque (Comum) adicional; acerto → Salvaguarda de Constituição ou "Envenenado" por 1 min.' },
    { nome: 'Passo de Névoa', desc: 'Reaparece a 1,5× ND; +2 CR contra a próxima jogada de ataque.' },
    { nome: 'Resina Imobilizante', desc: 'Alvo a 6m: Salvaguarda de Agilidade ou "Impedido" até o próximo turno do espírito.' },
    { nome: 'Vinha Súbita', desc: 'Alvo a 3× ND: Salvaguarda de Força ou "Agarrado" (escapa com Teste de Força vs CD).' },
    { nome: 'Pulso Estonteante', recarga: '5-6', desc: 'Pulso de energia; alvo a 3× ND: Salvaguarda de Intelecto ou "Atordoado" até o próximo turno.' },
    { nome: 'Maldição da Lentidão', desc: 'Gravidade num alvo a 3× ND: Salvaguarda de Força ou "Pesado" até o próximo turno do espírito.' },
    { nome: 'Toque Debilitante', desc: 'Toque a 1,5m: até o próximo turno, o alvo causa metade do dano com ataques de Força.' },
    { nome: 'Lâmina Sangrenta', desc: 'Ataque (Comum) adicional; acerto → "Sangramento".' },
    { nome: 'Toque Gélido', desc: 'Toque a 1,5m: ⅓ND d6 de frio + Salvaguarda de Constituição ou "Hipotérmico".' },
    { nome: 'Toque Flamejante', desc: 'Ataque (Comum) adicional com ⅓ND d6 de fogo; acerto → "Queimado".' },
    { nome: 'Grito de Pavor', desc: 'Alvo a 3× ND: Salvaguarda de Sabedoria ou "Amedrontado" (+"Caído" se falhar muito).' },
    { nome: 'Tropeço Espectral', desc: 'Alvo a 3m: Salvaguarda de Agilidade ou "Caído".' },
    { nome: 'Maldição Silenciadora', desc: 'Alvo a 3× ND: Salvaguarda de Intelecto ou "Mudo" até o próximo turno do espírito.' },
    { nome: 'Corromper a Mente', desc: 'Alvo a 3× ND: Salvaguarda de Presença ou "Alucinado" até o próximo turno.' },
    { nome: 'Garra Trêmula', desc: 'Toque a 1,5m: Salvaguarda de Constituição ou "Estremecido" até o próximo turno.' },
    { nome: 'Toque Drenante', desc: 'Toque a 1,5m: ⅓ND d6 de dano e cura igual ao dano.' },
    { nome: 'Maldição da Exaustão', recarga: '5-6', desc: 'Alvo a 3× ND: Salvaguarda de Constituição ou +1 nível de "Exausto".' },
    { nome: 'Espinhos Súbitos', desc: 'Até o próximo turno, atacantes corpo-a-corpo sofrem 1d6 perfurante.' },
    { nome: 'Manto de Escuridão', desc: 'Escuridão em 3m: criaturas sem visão no escuro ficam "Cego".' },
    { nome: 'Salto Esmagador', desc: 'Salta perto de um alvo a 6m: Salvaguarda de Força ou "Caído".' },
    { nome: 'Toque Embriagante', desc: 'Alvo a 3m: Salvaguarda de Constituição ou "Bêbado" até o próximo turno.' },
    { nome: 'Marca da Morte', desc: 'Marca um alvo a 3× ND: o próximo dano nele é +½ND.' },
    { nome: 'Bruma Tóxica', desc: 'Cone de 3m: Salvaguarda de Constituição ou "Envenenado" até o próximo turno.' },
    { nome: 'Reflexo Acelerado', desc: 'Até o próximo turno: +2 CR e vantagem em Salvaguardas de Agilidade.' },
    { nome: 'Olhar Confuso', desc: 'Alvo a 3× ND: Salvaguarda de Presença ou ataca um alvo aleatório no próximo turno.' },
    { nome: 'Sopro Paralisante', recarga: '5-6', desc: 'Alvo a 6m: Salvaguarda de Constituição ou "Paralisado" até o próximo turno.' },
    { nome: 'Carga Trovejante', desc: 'Avança num alvo a 6m: ⅓ND d6 trovejante + Salvaguarda de Constituição ou "Atordoado".' },
    { nome: 'Faísca Reativa', desc: 'Ataque (Comum) adicional com ⅓ND d6 elétrico; acerto → sem reações até o próximo turno do espírito.' },
    { nome: 'Olhar Imobilizante', desc: 'Alvo a 3m: Salvaguarda de Intelecto ou "Impedido" até o próximo turno.' },
    { nome: 'Sussurro Desencorajador', desc: 'Alvo a 3× ND: Salvaguarda de Presença ou desvantagem na próxima rolagem de ataque.' },
    { nome: 'Toque Ácido', desc: 'Toque a 1,5m: ⅓ND d6 ácido e −1 de CR até o próximo turno.' },
    { nome: 'Convocar Frieza', desc: 'Alvo a 3× ND: Salvaguarda de Constituição ou deslocamento ÷2 até o próximo turno.' },
    { nome: 'Aperto Sufocante', desc: 'Alvo agarrado: Salvaguarda de Constituição ou "Sufocado".' },
    { nome: 'Investida Cega', desc: 'Até o fim do turno: vantagem nos ataques, mas ataques contra ele com vantagem.' },
  ],

  // ── Maldições — Habilidades de Reação (espírito) ─────────────────────────
  espiritoReacao: [
    { nome: 'Reflexo Amaldiçoado', desc: 'Ao ser alvo de ataque: +3 na própria CR (+1 a cada 5 de ND). Se o atacante errar, ataque (Comum) contra ele.' },
    { nome: 'Distorção Defensiva', desc: 'Reduz o dano sofrido em d8 = ND. Uma vez por rodada, mesmo com várias reações.' },
    { nome: 'Rejeição Violenta', desc: 'Quando atacado por criatura a até 3m: ela faz Salvaguarda de Força ou é empurrada 1,5m × ND e fica "Caído".' },
    { nome: 'Movimento Maldito', desc: 'Ao ser alvo de ataque (Comum): desaparece e reaparece a até 1,5× ND, desviando automaticamente.' },
    { nome: 'Apetite Voraz', recarga: '4-6', desc: 'Ao ser alvo de ataque que gaste PA: reduz o dano em d8 = ½ ND e recupera PV igual ao dano reduzido.' },
    { nome: 'Visão da Desgraça', recarga: '4-6', desc: 'Quando criatura a até 3× ND atacar/conjurar/usar habilidade com PA: Salvaguarda de Sabedoria; falha → 1d8 psíquico por PA consumido e a técnica falha.' },
    { nome: 'Persistência Maldita', desc: 'Quando seria reduzido a 0 PV, desaparece e reaparece a até 3× ND com 1 PV. Recupera após 10 minutos.' },
    { nome: 'Marca Reativa', desc: 'Ao sofrer dano de uma criatura, marca-a: vantagem nas rolagens de ataque contra ela até o início do próximo turno.' },
    { nome: 'Ruptura de Concentração', desc: 'Ao sofrer crítico: cancela todas as habilidades do alvo que exijam "Concentração" e uma habilidade aleatória de 1 min ou mais.' },
    { nome: 'Corpo Intangível', desc: 'Ao sofrer qualquer dano: reduz pela metade e torna-se intangível até o fim do turno.' },
    { nome: 'Eco Violento', recarga: '4-6', desc: 'Ao sofrer qualquer dano: o atacante sofre d8 psíquico = ½ ND.' },
    { nome: 'Aura de Lentidão', desc: 'Ao ser alvo de ataque/técnica: aura em 3m; criaturas fazem Salvaguarda de Sabedoria; falha → só 1 ataque (Comum) por turno até o fim do turno delas.' },
    { nome: 'Deslocamento Caótico', desc: 'Ao ser alvo de ataque (Comum) à distância: redireciona para outra criatura a até 3m. Se ND 12+, também redireciona técnicas (recarga 5-6).' },
    { nome: 'Contra-Investida', desc: 'Quando uma criatura erra um ataque contra o espírito: ataque (Comum) imediato contra ela.' },
    { nome: 'Casca Refletora', desc: 'Ao sofrer dano à distância: reflete metade ao atacante (Salvaguarda de Agilidade reduz).' },
    { nome: 'Espinhos Reativos', desc: 'Ao ser atingido em CaC: o atacante sofre d8 perfurante = ½ ND.' },
    { nome: 'Recuo Fantasma', desc: 'Ao ser alvo de ataque: torna-se intangível e desliza 1,5× ND; se sair do alcance, o ataque falha.' },
    { nome: 'Maldição de Espelho', desc: 'Ao falhar numa Salvaguarda forçada: obriga a criatura à mesma Salvaguarda.' },
    { nome: 'Substituição Sombria', desc: 'Ao ser alvo de ataque: troca de lugar com aliado a 3× ND, que vira o alvo.' },
    { nome: 'Lufada Repulsora', desc: 'Quando criatura entra a 1,5m: Salvaguarda de Força ou empurrada 3m e "Caído".' },
    { nome: 'Grito de Dor', recarga: '5-6', desc: 'Ao sofrer dano: criaturas a 3m fazem Salvaguarda de Constituição ou "Atordoado".' },
    { nome: 'Absorção Parcial', desc: 'Ao sofrer dano: reduz d8 = ½ ND e recupera PV = metade do reduzido.' },
    { nome: 'Olhar Mortal', desc: 'Quando atacado: o atacante faz Salvaguarda de Sabedoria ou "Amedrontado".' },
    { nome: 'Endurecimento Reflexo', desc: 'Ao ser alvo de ataque: +½ ND (arred. p/ baixo) na CR contra ele.' },
    { nome: 'Substância Viscosa', desc: 'Ao ser atingido em CaC: o atacante faz Salvaguarda de Agilidade ou "Impedido".' },
    { nome: 'Resposta Tóxica', desc: 'Ao sofrer dano CaC: o atacante faz Salvaguarda de Constituição ou "Envenenado".' },
    { nome: 'Distorção Evasiva', recarga: '5-6', desc: 'Contra efeito de Salvaguarda de Agilidade por dano: sucesso automático, sem dano.' },
    { nome: 'Casulo Instantâneo', recarga: '4-6', desc: 'Contra dano alto de uma vez: reduz à metade e resistência a tudo até o próximo turno, mas "Incapacitado".' },
    { nome: 'Eco da Agonia', desc: 'Quando criatura a 3× ND cai a 0 PV: recupera 1d8 PV e vantagem no próximo ataque.' },
    { nome: 'Reflexo Espinhoso', desc: 'Quem inicia o turno agarrando/agarrado pelo espírito sofre d6 perfurante = ½ ND.' },
    { nome: 'Pulso de Pânico', recarga: '5-6', desc: 'Ao cair abaixo de metade dos PV: criaturas a 3× ND fazem Salvaguarda de Presença ou "Amedrontado".' },
    { nome: 'Maldição de Troca', desc: 'Ao sofrer crítico: transfere metade do dano a um aliado a 3m, sem resistência.' },
    { nome: 'Contra-Veneno', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Constituição ou "Envenenado".' },
    { nome: 'Repelir Sombrio', desc: 'Alvo de ataque: o atacante faz Salvaguarda de Força ou é empurrado 3m e "Caído".' },
    { nome: 'Grito Reativo', recarga: '5-6', desc: 'Ao sofrer dano: criaturas a 3m fazem Salvaguarda de Constituição ou "Atordoado".' },
    { nome: 'Pele Gélida', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Constituição ou "Hipotérmico".' },
    { nome: 'Cinzas Reativas', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Agilidade ou "Queimado".' },
    { nome: 'Vínculo Doloroso', desc: 'Ao sofrer dano: o atacante leva metade desse dano como psíquico.' },
    { nome: 'Reflexo Cegante', desc: 'Alvo de ataque: o atacante faz Salvaguarda de Intelecto ou "Cego".' },
    { nome: 'Lamento Reflexo', desc: 'Ao sofrer dano: o atacante faz Salvaguarda de Constituição ou "Surdo".' },
    { nome: 'Teia Reativa', desc: 'Atacado de perto: o alvo faz Salvaguarda de Agilidade ou "Impedido".' },
    { nome: 'Maldição Espinhenta', desc: 'Atingido em CaC: o atacante sofre ⅓ND d6 perfurante + Salvaguarda de Constituição ou "Sangramento".' },
    { nome: 'Bruma Defensiva', desc: 'Alvo de ataque à distância: o atacante tem desvantagem.' },
    { nome: 'Recuo Tóxico', recarga: '4-6', desc: 'Alvo de ataque: recua 1,5× ND e deixa nuvem de veneno ("Envenenado").' },
    { nome: 'Aura de Terror Reflexa', recarga: '5-6', desc: 'Abaixo da metade do PV: criaturas a 3× ND fazem Salvaguarda de Sabedoria ou "Amedrontado".' },
    { nome: 'Lentidão Punitiva', desc: 'Atingido: o atacante faz Salvaguarda de Constituição ou deslocamento ÷2.' },
    { nome: 'Resposta Atordoante', desc: 'Ao sofrer crítico: o atacante faz Salvaguarda de Constituição ou "Atordoado".' },
    { nome: 'Drenar ao Ferir', desc: 'Ao sofrer dano CaC: recupera ½ND Pontos de Vida.' },
    { nome: 'Maldição da Queda', desc: 'Quem erra CaC nele: Salvaguarda de Agilidade ou "Caído".' },
    { nome: 'Eco Mental', desc: 'Criatura a 3× ND usa técnica: Salvaguarda de Presença ou ⅓ND d6 psíquico.' },
    { nome: 'Sopro Reativo', recarga: '4-6', desc: 'Criatura entra a 3m: Salvaguarda de Agilidade ou ⅓ND d6.' },
    { nome: 'Explosão Defensiva', recarga: '5-6', desc: 'Ao sofrer dano: criaturas a 3m sofrem ⅓ND d6 fogo + Salvaguarda de Agilidade ou "Queimado".' },
    { nome: 'Permuta Ilusória', desc: 'Alvo de ataque: troca com uma ilusão a 3× ND; o ataque falha.' },
    { nome: 'Olhar Endurecedor', desc: 'Ao ser atacado: o atacante faz Salvaguarda de Constituição ou "Impedido".' },
    { nome: 'Resposta Sonora', desc: 'Ao sofrer dano: o atacante sofre ⅓ND d6 trovejante + Salvaguarda de Constituição ou "Surdo".' },
    { nome: 'Reflexo Apavorante', desc: 'Ao ser atacado: o atacante faz Salvaguarda de Sabedoria ou "Amedrontado" + desvantagem.' },
    { nome: 'Carapaça Reativa', desc: 'Ao sofrer dano: +2 CR e resistência ao tipo de dano até o próximo turno.' },
    { nome: 'Veneno Borbulhante', desc: 'Ao sofrer dano: criaturas a 1,5m fazem Salvaguarda de Constituição ou "Envenenado".' },
    { nome: 'Frieza Punitiva', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Constituição ou "Hipotérmico" + lento.' },
    { nome: 'Esporos Reativos', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Constituição ou "Sonolento".' },
    { nome: 'Recuo Instantâneo', desc: 'Alvo de ataque: desloca 3m sem provocar reações.' },
    { nome: 'Maldição do Eco', desc: 'Criatura a 3× ND conjura técnica com PEA: sofre ⅓ND d6 de energia.' },
    { nome: 'Punir Movimento', desc: 'Criatura sai do alcance CaC: sofre ⅓ND d6 + Salvaguarda de Agilidade ou "Impedido".' },
    { nome: 'Casulo de Trevas', desc: 'Ao sofrer dano: ataques contra ele com desvantagem até o próximo turno.' },
    { nome: 'Resposta Ácida', desc: 'Atingido em CaC: a arma/membro do atacante corrói (−1 de dano cumulativo).' },
    { nome: 'Grito Final', desc: 'Ao chegar a 0 PV: criaturas a 3× ND fazem Salvaguarda de Constituição ou "Atordoado".' },
    { nome: 'Maldição Reativa do Peso', desc: 'Ao ser atacado: o atacante faz Salvaguarda de Força ou "Pesado".' },
    { nome: 'Reflexo Embriagante', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Constituição ou "Bêbado".' },
    { nome: 'Espelho Doloroso', desc: 'Forçado a Salvaguarda: obriga a criatura à mesma Salvaguarda (mesmo efeito).' },
    { nome: 'Aura de Decadência', desc: 'Ao sofrer dano: criaturas a 1,5m têm desvantagem na próxima rolagem de ataque.' },
    { nome: 'Contra-Olhar', desc: 'Atacado por visão: o atacante faz Salvaguarda de Intelecto ou "Cego".' },
    { nome: 'Rejeição Paralisante', recarga: '5-6', desc: 'Atingido em CaC: o atacante faz Salvaguarda de Constituição ou "Paralisado".' },
  ],

  // ── Habilidades com Barreiras ────────────────────────────────────────────
  barreira: [
    { nome: 'Santuário da Morte', desc: 'Barreira de espaço com caveiras/ossos. Enquanto manifestada, o usuário causa +2 dados em ataques/técnicas e recebe +1 de CR.' },
    { nome: 'Estreito Espaço-Temporal', desc: 'Túnel/corredor que refaz o loop a cada 30m; 1h dentro = 1 dia fora. Cada loop perde 10 PA da Energia Total; Salvaguarda de Sabedoria CD 18 para notar/localizar o criador.' },
    { nome: 'Inferno Sacrifical', desc: 'Caverna com núcleos/espíritos menores. A cada morte por essa maldição, forma-se um núcleo. Sacrifica núcleos: +20 PV / +1 dado de dano (máx 2) / +1 CD por sacrifício. Cada núcleo: 30 PV, 15 CR.' },
    { nome: 'Loop Temporal Completo', desc: 'Volta o tempo de coisas orgânicas a cada X horas. Ao voltar, todos perdem memórias (Teste de Intelecto CD 20 retém 5 min). Tem um núcleo a ser desativado.' },
    { nome: 'Espaço do Sono Eterno', desc: 'Coloca criaturas para dormir. A cada 1 min, Salvaguarda de Constituição CD 1 (sobe +1 por minuto); falha → dorme até sofrer dano/ser acordada. Eventualmente morrem de fome/sede.' },
  ],
};

// Rótulos das categorias + lista da ficha onde a entrada é inserida + `tipo` de
// NPC que pode usá-la. Traços animais/criatura e habilidades de espírito/barreira
// são de MALDIÇÃO. Humanos (feiticeiros) usam só estilo + manipulação.
export const CATALOG_GROUPS = [
  { key: 'aspecto',        label: 'Aspectos',                 target: 'aspectos',  tipo: 'maldicao' },
  { key: 'acaoBonus',      label: 'Ações Bônus (criatura)',   target: 'hab_bonus', tipo: 'maldicao' },
  { key: 'acaoPoder',      label: 'Ações de Poder (criatura)', target: 'hab_poder', tipo: 'maldicao' },
  { key: 'reacao',         label: 'Reações (criatura)',       target: 'hab_reacao', tipo: 'maldicao' },
  { key: 'espiritoPoder',  label: 'Maldição — Ação de Poder', target: 'hab_poder', tipo: 'maldicao' },
  { key: 'espiritoBonus',  label: 'Maldição — Ação Bônus',    target: 'hab_bonus', tipo: 'maldicao' },
  { key: 'espiritoReacao', label: 'Maldição — Reação',        target: 'hab_reacao', tipo: 'maldicao' },
  { key: 'barreira',       label: 'Barreiras',                target: 'aspectos',  tipo: 'maldicao' },
];
